{"abstract":[{"text":"Internal error with an associated error code that can be provided to Sightic Analytics for troubleshooting.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/sighticanalytics\/sighticerror\/internalerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics","doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/internalError(_:)"},"sections":[],"metadata":{"externalID":"s:16SighticAnalytics0A5ErrorO08internalC0yACSicACmF","modules":[{"name":"SighticAnalytics"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"SighticError.internalError(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics":{"type":"topic","title":"SighticAnalytics","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics","kind":"symbol","url":"\/documentation\/sighticanalytics","role":"collection","abstract":[{"text":"Predict whether a person is impaired due to alcohol consumption.","type":"text"}]},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError/internalError(_:)":{"kind":"symbol","url":"\/documentation\/sighticanalytics\/sighticerror\/internalerror(_:)","role":"symbol","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/internalError(_:)","abstract":[{"text":"Internal error with an associated error code that can be provided to Sightic Analytics for troubleshooting.","type":"text"}],"title":"SighticError.internalError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SighticError"}],"title":"SighticError","url":"\/documentation\/sighticanalytics\/sighticerror","kind":"symbol","abstract":[{"text":"Error that occurs during the analysis of a test recording by the Sightic Analytics backend.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SighticError"}],"role":"symbol","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError"}}}